Add option for multiple custom menu modifiers
IPVP-MC/canvas pull request #10
Opened 2021-03-16 21:44 UTC by FreshLlamanade

I feel that allowing for more than one custom menu modifier would be a meaningful addition to the AbstractPaginatedMenuBuilder class.

- Changed attribute newMenuModifier into a List initialized in the constructor
- Added null check in method newMenuModifier()
- Added method newMenuModifiers() to add multiple menu consumers at once
- Rather than just applying a single menu modifier, the Builder classes now iterate through the modifier list and apply all of them in order

2021-03-17 15:11 UTC, sainttx requested changes
Nice little change,  just a few things and I'll get it merged in. Thanks for the PR! 😄

2021-03-17 15:11 UTC, sainttx commented on src/main/java/org/ipvp/canvas/paginate/PaginatedMenuBuilder.java
> +                for (Consumer<Menu> menuModifier : getNewMenuModifiers())
Please add braces to if-statements
```suggestion
                for (Consumer<Menu> menuModifier : getNewMenuModifiers()) {
```

2021-03-20 01:26 UTC, FreshLlamanade commented
Got it. Those changes are in!

2021-04-18 20:17 UTC, sainttx approved these changes

2021-04-18 20:18 UTC, merged

2021-04-18 20:18 UTC, sainttx commented
Thanks for the changes @FreshLlamanade!